// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"
)

type GatewayIDMapping struct {
	ID                 int64  `json:"id"`
	GatewayID          string `json:"gateway_id"`
	Token              string `json:"token"`
	MerchantPrivateKey string `json:"merchant_private_key"`
}

type TokenCache struct {
	ID                 int64     `json:"id"`
	CredentialsHash    string    `json:"credentials_hash"`
	AccessToken        string    `json:"access_token"`
	AccessRefreshedAt  time.Time `json:"access_refreshed_at"`
	RefreshToken       string    `json:"refresh_token"`
	RefreshRefreshedAt time.Time `json:"refresh_refreshed_at"`
}
